#+HUGO_FRONT_MATTER_FORMAT: toml
#+hugo_base_dir: ../../

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t


* Recent publications
** Design and manufacturing of a VAWT scale model                      :VAWT:fablab:
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./publication/vawt_design
:EXPORT_FILE_NAME: index 
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :featured true :doi "10.1016/j.jweia.2019.103949"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :publication "Journal of Wind Engineering and Industrial Aerodynamics, 193, 103949 (2019)"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :authors '("A. Vergaerde" "T. De Troyer" "A. Carbó Molina" "L. Standaert" "M.C. Runacres")
:EXPORT_DATE: 2020-04-10
:END:

This paper describes the 
design, manufacturing and validation of a vertical-axis wind turbine setup for
wind tunnel tests. 

#+hugo: more

The potential of vertical-axis wind turbines (VAWTs) for specific applications
(floating off-shore or urban in- stallations) has been reconsidered in recent
years. This renewed interest has led to an increasing number of experimental
studies on VAWTs. A challenge of experimental work is correctly interpreting
experimental results but just as important is the design of the experimental
setup. 

The objective of the present study is to elaborate on the complete
development process of a VAWT wind tunnel test setup, from design to aerodynamic
interpretation. The effect of the design choices and structural characteristics
of the setup can be traced in the measured torque. The influence of structural
dynamics of an experimental setup are proven to influence unsteady measurements
significantly through the analysis of the spectral content of the measured
torque. An extensive modal analysis of the VAWT rotor allows to link modal
vibrations to their contaminating effect on the measured torque. In addition,
the dynamics of the sensors and setup are found to be important contributions to
the contamination of dynamic measurements. To interpret unsteady torque
measurements, the complete experimental setup needs to be dynamically
characterised. 


---

** Experimental validation of the power enhancement of a pair of vertical-axis wind turbines :fablab:VAWT:
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./publication/vawt_enhancement
:EXPORT_FILE_NAME: index 
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :authors '("Antoine Vergaerde" "Tim De Troyer" "Lieven Standaert" "Joanna Kluczewska-Bordier" "Denis Pitance" "Alexandre Immas" "Frédéric Silvert""Mark C. Runacres")
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :featured true :doi "10.1016/j.renene.2019.06.115"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :publication "Renewable Energy, 146, 181-187 (2020)"
:EXPORT_DATE: 2020-04-10
:END:

Wind tunnel tests have been performed of individual and paired H-type Darrieus
vertical-axis wind turbines. The turbines in the paired configuration are
closely spaced, at 1.2 and 1.3 rotor diameters shaft to shaft, and are
counter-rotating. 

#+hugo: more

Two directions of rotation were studied, one where the facing
(inner) blades move along with the incoming flow, and one where the facing
blades move against the wind. The wind tunnel tests confirm a net increase in
the power coefficient of the paired configuration compared with twice the power
coefficient of the individual turbine. We found average relative increases in
the power coefficients between 13% and 16%, which is consistent with numerical
studies available in the literature. 



---

** Feasibility and performance assessment of small and medium-sized wind turbines :fablab:VAWT:
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./publication/smwt_jochem
:EXPORT_FILE_NAME: index 
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :authors '("Jochem Vermeir")
:EXPORT_DATE: 2015-04-10
:END:

There is considerable uncertainty about the role that small and medium wind
turbines may play in the production of sustainable electricity. In the present
work, we identify the main factors affecting the economic viability of small and
medium wind turbines (herafter SMWTs). We then propose a framework for more
efficient and reliable predictions of the annual energy production of SMWTs. 

#+hugo: more

We
demonstrate that these turbines are indeed profitable, provided that an
appropriate turbine is selected and that the annual energy production is
estimated carefully. These seemingly simple tasks are non-trivial and current
practices too often lead to unreliable assessments. 

We first assemble a database of wind turbines with a rated power up to 100 kW.
Such a database is a necessary tool when assessing the feasibility of a project
involving SMWTs, since the market is very immature, with a wide variation in
quality between different turbines. 

We then calculate the annual energy production (AEP) for a number of measurement
sites in Belgium and The Netherlands and for different independently-tested
SMWTs. Based on these data and on first principles, we show what the best
methods are to select an appropriate turbine and what the expected accuracy is
of the AEP estimate.  
We have found that a particular statistical error has been overlooked in the
current methods to estimate the annual energy production. This error is the
possible mismatch of the averaging times with which wind speeds and turbine
power outputs are sampled. Using wind speed and power measurements, we show how
this error can be minimised. 

Our findings have an immediate practical importance. We therefore apply our
methods in a number of case studies, and give recommendations for future SMWT
projects. 

---
